version: "3.3"
services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db
  web:
    image: nginx
    container_name: yii_nginx
    tty: true
    ports:
      - 81:80
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    image: mysql:8.0
    command: mysqld --user=root
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=yii
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii
      - MYSQL_DATABASE=admin
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - TZ=Asia/Tokyo
      - PMA_HOST=db
      - PMA_USER=yii
      - PMA_PASSWORD=yii
    ports:
      - 4040:80
